import { z } from 'zod';
import { router, publicProcedure } from '@/server/trpc/trpc';
import { getControlDb } from '@amisimedos/db/client';
import { DeploymentTier, FacilityType } from '@amisimedos/constants';
import { hashPassword } from '@amisimedos/db/lib/crypto';
import { notifyPaymentSuccess } from '@/app/actions/core-actions';

/**
 * Public Router
 * Used for unauthenticated processes like onboarding/checkout.
 */
export const publicRouter: any = router({
    
    // ─── Public Checkout & Onboarding ──────────────────────────────────
    checkoutTenant: publicProcedure
        .input(z.object({
            name: z.string().min(3),
            slug: z.string().min(3).regex(/^[a-z0-9-]+$/),
            region: z.string(),
            tier: z.nativeEnum(DeploymentTier),
            facilityType: z.nativeEnum(FacilityType).default('CLINIC'),
            adminName: z.string().min(2),
            adminEmail: z.string().email(),
            adminPassword: z.string().min(8),
            // Payment info (optional for 14-day free trial)
            paypalOrderId: z.string().optional().default('FREE_TRIAL'),
            amountPaid: z.number().optional().default(0),
            isAnnual: z.boolean().optional().default(false),
            isTrial: z.boolean().optional().default(false),
        }))
        .mutation(async ({ input }: any) => {
            const db = getControlDb();

            // 1. Provision Tenant Database & Environment
            const { provisionTenant } = await import('@amisimedos/db/management');
            const passwordHash = await hashPassword(input.adminPassword);

            // Fetch default modules for the facility type
            const modules = await db.module.findMany();
            // Just enable everything for now, or match existing logic
            const enabledModulesMap: Record<string, boolean> = {};
            modules.forEach(m => enabledModulesMap[m.code.toLowerCase()] = true);
            const moduleConfig: Record<string, { enabled: boolean; version: string }> = {};
            modules.forEach(m => { moduleConfig[m.code] = { enabled: true, version: '1.0.0' }; });

            await provisionTenant(
                input.name,
                input.slug,
                input.region,
                '', // DB URL auto generated by Neon
                input.tier,
                {}, // settings
                enabledModulesMap,
                { name: input.adminName, email: input.adminEmail, passwordHash }
            );

            // 2. Fetch the newly created tenant from Control Plane
            const tenant = await db.tenant.findUnique({ where: { slug: input.slug } });
            
            if (tenant) {
                const isFreeTrial = input.paypalOrderId === 'FREE_TRIAL' || input.amountPaid === 0 || input.isTrial;
                const trialEndsAt = isFreeTrial ? new Date(Date.now() + 14 * 24 * 60 * 60 * 1000) : null;

                // Auto-activate tenant immediately upon automatic onboarding & provisioning
                await db.tenant.update({
                    where: { id: tenant.id },
                    data: { 
                        status: 'active',
                        trialEndsAt,
                        facilityType: input.facilityType,
                        moduleConfig: moduleConfig as any,
                        workflowCustomization: {
                            queue_logic: { triage_levels: ['Critical', 'Urgent', 'Routine'] },
                            billing_rules: { currency: 'USD', tax_rate: 0 },
                            staff_roles: {}
                        }
                    }
                });

                // Attach Module Entitlements
                await db.tenantModule.createMany({
                    data: modules.map(m => ({
                        tenantId: tenant.id,
                        moduleId: m.id,
                        isEnabled: true,
                    }))
                });

                // Auto-create Subscription record if matching plan exists
                try {
                    const plan = await db.plan.findFirst({
                        where: { OR: [{ code: input.tier }, { name: { contains: input.tier, mode: 'insensitive' } }] }
                    });
                    if (plan) {
                        await db.subscription.create({
                            data: {
                                tenantId: tenant.id,
                                planId: plan.id,
                                status: 'ACTIVE',
                                startDate: new Date(),
                                endDate: trialEndsAt,
                                autoRenew: !isFreeTrial
                            }
                        });
                    }
                } catch (subErr) {
                    console.warn('[AutoProvision] Subscription auto-attach warning:', subErr);
                }

                // 3. Log the Payment or Trial Activation to SystemPayment table
                const payment = await db.systemPayment.create({
                    data: {
                        tenantId: tenant.id,
                        amount: isFreeTrial ? 0 : input.amountPaid,
                        currency: 'USD',
                        method: isFreeTrial ? 'FREE_TRIAL' : 'PAYPAL',
                        status: 'COMPLETED',
                        reference: input.paypalOrderId || 'FREE_TRIAL_14_DAYS',
                        customerEmail: input.adminEmail,
                        customerName: input.adminName,
                        description: isFreeTrial 
                            ? `AmisiMedOS 14-Day Free Trial - ${input.tier} (No Card Required)` 
                            : `AmisiMedOS ${input.tier} (${input.isAnnual ? 'Yearly' : 'Monthly'})`,
                    }
                });

                // 4. Send Confirmation and Admin Alert Emails
                await notifyPaymentSuccess(tenant, payment, input);
            }

            return { success: true, tenant };
        }),
});
