import { z } from 'zod';
import { router, publicProcedure } from '@/server/trpc/trpc';
import { getControlDb } from '@amisimedos/db/client';
import { DeploymentTier, FacilityType } from '@amisimedos/constants';
import { hashPassword } from '@amisimedos/db/lib/crypto';
import { notifyPaymentSuccess } from '@/app/actions/system-actions';

/**
 * Public Router
 * Used for unauthenticated processes like onboarding/checkout.
 */
export const publicRouter: any = router({
    
    // ─── Public Checkout & Onboarding ──────────────────────────────────
    checkoutTenant: publicProcedure
        .input(z.object({
            name: z.string().min(3),
            slug: z.string().min(3).regex(/^[a-z0-9-]+$/),
            region: z.string(),
            tier: z.nativeEnum(DeploymentTier),
            facilityType: z.nativeEnum(FacilityType).default('CLINIC'),
            adminName: z.string().min(2),
            adminEmail: z.string().email(),
            adminPassword: z.string().min(8),
            // Payment info
            paypalOrderId: z.string(),
            amountPaid: z.number(),
            isAnnual: z.boolean(),
        }))
        .mutation(async ({ input }: any) => {
            const db = getControlDb();

            // 1. Provision Tenant Database & Environment
            const { provisionTenant } = await import('@amisimedos/db/management');
            const passwordHash = await hashPassword(input.adminPassword);

            // Fetch default modules for the facility type
            const modules = await db.module.findMany();
            // Just enable everything for now, or match existing logic
            const enabledModulesMap: Record<string, boolean> = {};
            modules.forEach(m => enabledModulesMap[m.code.toLowerCase()] = true);
            const moduleConfig: Record<string, { enabled: boolean; version: string }> = {};
            modules.forEach(m => { moduleConfig[m.code] = { enabled: true, version: '1.0.0' }; });

            await provisionTenant(
                input.name,
                input.slug,
                input.region,
                '', // DB URL auto generated by Neon
                input.tier,
                {}, // settings
                enabledModulesMap,
                { name: input.adminName, email: input.adminEmail, passwordHash }
            );

            // 2. Fetch the newly created tenant from Control Plane
            const tenant = await db.tenant.findUnique({ where: { slug: input.slug } });
            
            if (tenant) {
                // Attach Module Entitlements
                await db.tenantModule.createMany({
                    data: modules.map(m => ({
                        tenantId: tenant.id,
                        moduleId: m.id,
                        isEnabled: true,
                    }))
                });

                // Update configuration
                await db.tenant.update({
                    where: { id: tenant.id },
                    data: {
                        facilityType: input.facilityType,
                        moduleConfig: moduleConfig as any,
                        workflowCustomization: {
                            queue_logic: { triage_levels: ['Critical', 'Urgent', 'Routine'] },
                            billing_rules: { currency: 'USD', tax_rate: 0 },
                            staff_roles: {}
                        }
                    }
                });

                // 3. Log the Payment to SystemPayment table
                const payment = await db.systemPayment.create({
                    data: {
                        tenantId: tenant.id,
                        amount: input.amountPaid,
                        currency: 'USD',
                        method: 'PAYPAL',
                        status: 'COMPLETED',
                        reference: input.paypalOrderId,
                        customerEmail: input.adminEmail,
                        customerName: input.adminName,
                        description: `AmisiMedOS ${input.tier} (${input.isAnnual ? 'Yearly' : 'Monthly'})`,
                    }
                });

                // 4. Send Confirmation and Admin Alert Emails
                await notifyPaymentSuccess(tenant, payment, input);
            }

            return { success: true, tenant };
        }),
});
