name: amisi_mobile
description: Amisi HealthOS Staff Mobility Application.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.2
  path: ^1.8.3
  connectivity_plus: ^5.0.2
  dio: ^5.4.1
  provider: ^6.1.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.16.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
