/**
 * Real-Time Event Types for AmisiMedOS
 */

export type RealtimeEventType = 
  | 'PATIENT_MUTATED' 
  | 'VITALS_UPDATED' 
  | 'MEDICATION_DISPENSED' 
  | 'LAB_RESULT_READY'
  | 'ADMISSION_UPDATED'
  | 'INVENTORY_ALERT'
  | 'LAB_ORDERED'
  | 'SPECIMEN_COLLECTED'
  | 'RESULTS_INGESTED'
  | 'LAB_REPORT_VALIDATED'
  | 'CRITICAL_LAB_ALERT'
  | 'PATIENT_ADMITTED'
  | 'PATIENT_TRANSFERRED'
  | 'PATIENT_DISCHARGED'
  | 'PO_SENT'
  | 'PO_APPROVAL_REQUIRED'
  | 'INVENTORY_RESTOCKED'
  | 'DIAGNOSTIC_ORDERED'
  | 'CRITICAL_RESULT_ALARM'
  | 'TRAUMA_ALARM'
  | 'ROI_REQUESTED'
  | 'ROI_APPROVED'
  | 'EMPLOYEE_ONBOARDED'
  | 'SHIFT_ASSIGNED'
  | 'LEAVE_APPROVED'
  | 'LEAVE_REJECTED'
  | 'ICU_ADMISSION'
  | 'VENTILATOR_UPDATED'
  | 'ICU_DISCHARGE'
  | 'BED_STATUS_CHANGED'
  | 'MAR_UPDATED'
  | 'PRESCRIPTION_RECEIVED'
  | 'PRESCRIPTION_DISPENSED'
  | 'CONTROLLED_SUBSTANCE_DISPENSED'
  | 'RADIOLOGY_ORDERED'
  | 'STUDY_ACQUIRED'
  | 'SURGERY_REQUESTED'
  | 'SURGERY_SCHEDULED'
  | 'ICU_ADMISSION_PENDING'
  | 'TREATMENT_CREATED'
  | 'CHEMO_STARTED'
  | 'PAYSLIP_READY'
  | 'INVENTORY_DISPENSED'
  | 'PAYMENT_RECEIVED'
  | 'ICU_ALARM'
  | 'HIGH_RISK_PREGNANCY'
  | 'LABOUR_STARTED'
  | 'PARTOGRAM_ALERT'
  | 'FOETAL_DISTRESS'
  | 'DELIVERY_COMPLETE'
  | 'NICU_ALERT'
  | 'MASSIVE_TRANSFUSION_ALERT'
  | 'CHEMO_HELD'
  | 'ONCOLOGY_EMERGENCY'
  | 'CRITICAL_RESULT_ALERT'
  | 'CREDENTIAL_EXPIRY_ALERT'
  | 'QUEUE_UPDATED'
  | 'CHAT_MESSAGE_RECEIVED';

export interface RealtimeEvent {
  tenantId: string;
  resource: string;
  id: string;
  type: RealtimeEventType;
  payload?: any;
  timestamp: string;
}
